package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AllowancePage extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs, rs2;
    String dd, dd1, dd2;
    String em1, em2,em3, em4,em5, em6,em7,em8,em9,em10;
    String ns, mt, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, t1, t2, t3, t4, rm;
    double ss, bs, hs, tr, ml, en, ul, ttl_M, ttl_A;
    double bsy, hsy, ty, mly, eny, uly, othy, giy;
    double b_sal;
    
    int rowCount = -1;
    public AllowancePage() {
        initComponents();
        
          
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(204, 0, 0));
        table.getTableHeader().setForeground(new Color(3, 3, 3));
        table.setRowHeight(40);
        
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
   
        /////
        
        try
            {
              
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            Statement st = connect.createStatement();
            rs = st.executeQuery("select * from Allow_vw_Table order by EmployeeID ASC");
            
                while(rs.next())
                {
                    em1=rs.getString("EmployeeID");
                    em2=rs.getString("Surname") + " " + rs.getString("First_name");
                    em3=rs.getString("Basic");
                    em4=rs.getString("Housing");
                    em5=rs.getString("Transport");
                    em6=rs.getString("Meal");
                    em7=rs.getString("Entertainment");
                    em8=rs.getString("Utility");
                    em9=rs.getString("Others");
                    em10=rs.getString("Gross_Income");
                    Object[] row = {em1,em2,em3,em4,em5,em6,em7,em8,em9,em10};
                    model.addRow(row);
                }
                
                         
            }
        catch(SQLException e)
            
            {
 
 
    System.out.println("Could not retrieve database metadata " + e.getMessage());
 
    }catch (ClassNotFoundException ex) {
                //Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        std_panel = new javax.swing.JPanel();
        txtSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMiddle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDPT = new javax.swing.JTextField();
        txtTrans = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGross = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMeal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEnter = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBasic = new javax.swing.JTextField();
        txtUtility = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnAdd_Student1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtHouse = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtOthers = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_panel.setBackground(new java.awt.Color(102, 102, 102));
        std_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        std_panel.setMinimumSize(new java.awt.Dimension(932, 611));
        std_panel.setPreferredSize(new java.awt.Dimension(932, 611));
        std_panel.setRequestFocusEnabled(false);
        std_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSurname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSurname.setEnabled(false);
        std_panel.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 250, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First name : ");
        std_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        txtFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirst.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFirst.setEnabled(false);
        std_panel.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 250, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Middle name : ");
        std_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        txtMiddle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMiddle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMiddle.setEnabled(false);
        std_panel.add(txtMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 30));

        jLabel11.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department : ");
        std_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 30));

        txtDPT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDPT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDPT.setEnabled(false);
        txtDPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPTActionPerformed(evt);
            }
        });
        std_panel.add(txtDPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 250, 30));

        txtTrans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTrans.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtTrans.setEnabled(false);
        std_panel.add(txtTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 150, 30));

        jLabel12.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(253, 253, 253));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("GROSS INCOME");
        std_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 200, 30));

        txtGross.setBackground(new java.awt.Color(251, 250, 250));
        txtGross.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGross.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGross.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtGross.setEnabled(false);
        txtGross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrossActionPerformed(evt);
            }
        });
        std_panel.add(txtGross, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 270, 30));

        jLabel13.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Housing:");
        std_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 30));

        txtMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMeal.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtMeal.setEnabled(false);
        std_panel.add(txtMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 150, 30));

        jLabel14.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Meal : ");
        std_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 90, 30));

        txtSalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSalary.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSalary.setEnabled(false);
        std_panel.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 250, 30));

        jLabel20.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Salary : ");
        std_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 30));

        btnUpdate1.setBackground(new java.awt.Color(163, 192, 192));
        btnUpdate1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(219, 6, 6));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/clr.png"))); // NOI18N
        btnUpdate1.setText("Clear");
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, 160, 40));

        jLabel19.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Surname : ");
        std_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        jLabel10.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Compute gross income for employee");
        std_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 380, 30));

        txtEnter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEnter.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtEnter.setEnabled(false);
        std_panel.add(txtEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 140, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("(10%)");
        std_panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 50, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Utility : ");
        std_panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 90, 30));

        jLabel24.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Basic (B) : ");
        std_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 90, 30));

        txtBasic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBasic.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtBasic.setEnabled(false);
        std_panel.add(txtBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 150, 30));

        txtUtility.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUtility.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtUtility.setEnabled(false);
        std_panel.add(txtUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 140, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPLOYEE ID", "NAME", "BASIC", "HOUSING", "TRANSPORT", "MEAL", "ENTERTAINMENT", "UTILITY", "OTHERS", "GROSS INCOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setRowMargin(2);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(9).setResizable(false);
        }

        std_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1090, 270));

        btnAdd_Student1.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student1.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/save.png"))); // NOI18N
        btnAdd_Student1.setText("Add Record");
        btnAdd_Student1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAdd_Student1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_Student1ActionPerformed(evt);
            }
        });
        std_panel.add(btnAdd_Student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 160, 40));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setEnabled(false);
        std_panel.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, 30));

        jLabel29.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Employee ID : ");
        std_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        btnCal.setBackground(new java.awt.Color(163, 192, 192));
        btnCal.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnCal.setForeground(new java.awt.Color(16, 107, 35));
        btnCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/cal.png"))); // NOI18N
        btnCal.setText("Calculate");
        btnCal.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        std_panel.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 160, 40));

        jLabel15.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Transport : ");
        std_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 90, 30));

        txtHouse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHouse.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        txtHouse.setEnabled(false);
        txtHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseActionPerformed(evt);
            }
        });
        std_panel.add(txtHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 150, 30));

        jLabel25.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Others Payables : ");
        std_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 140, 30));

        txtOthers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOthers.setText("0.0");
        std_panel.add(txtOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 140, 30));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Entertainment : ");
        std_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 130, 30));

        jLabel27.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("(40%)");
        std_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 50, 30));

        jLabel30.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("(30%)");
        std_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 50, 30));

        jLabel32.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("(10%)");
        std_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 50, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("(5%)");
        std_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 50, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("(5%)");
        std_panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 50, 30));

        jPanel3.add(std_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1130, 630));

        jPanel4.setBackground(new java.awt.Color(245, 245, 246));

        btnUpdate3.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate3.setText("HOME");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 80, 30));

        jLabel34.setBackground(new java.awt.Color(0, 204, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/logo.png"))); // NOI18N
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, 120, 70));

        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Employee Allowance");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 30));

        jPanel5.setBackground(new java.awt.Color(245, 245, 246));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setBackground(new java.awt.Color(0, 153, 255));
        jLabel28.setFont(new java.awt.Font("Perpetua", 2, 18)); // NOI18N
        jLabel28.setText("Search by ID or Surname : ");

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(16, 107, 35));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/sec.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 460, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPTActionPerformed

    private void txtGrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrossActionPerformed

    private void txtHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
        MainForm rs = new MainForm();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        //Calculating The Salary Allowance...
        if(!txtSalary.getText().equals("")){
            b_sal = Double.parseDouble(txtSalary.getText());
            double b_sal2 = b_sal * 12.0;
            ttl_A = Double.parseDouble(txtOthers.getText());
            double oth1y = ttl_A * 12.0;
            BigDecimal bd17 = new BigDecimal(Double.toString(oth1y));
            bd17 = bd17.setScale(2, RoundingMode.HALF_UP);
            othy = bd17.doubleValue();
            
            bs = (40.0/100.0)*b_sal;
            BigDecimal bd = new BigDecimal(Double.toString(bs));
            bd = bd.setScale(2, RoundingMode.HALF_UP);
            double bsd = bd.doubleValue();
            String bss = Double.toString(bsd);
            double bs1y = bsd * 12.0;
            BigDecimal bd11 = new BigDecimal(Double.toString(bs1y));
            bd11 = bd11.setScale(2, RoundingMode.HALF_UP);
            bsy = bd11.doubleValue();
            
            hs = (30.0/100.0)*b_sal;
            BigDecimal bd2 = new BigDecimal(Double.toString(hs));
            bd2 = bd2.setScale(2, RoundingMode.HALF_UP);
            double hsd = bd2.doubleValue();
            String hss = Double.toString(hsd);
            double hs1y = hsd * 12.0;
            BigDecimal bd12 = new BigDecimal(Double.toString(hs1y));
            bd12 = bd12.setScale(2, RoundingMode.HALF_UP);
            hsy = bd12.doubleValue();
            
            tr = (10.0/100.0)*b_sal;
            BigDecimal bd3 = new BigDecimal(Double.toString(tr));
            bd3 = bd3.setScale(2, RoundingMode.HALF_UP);
            double trd = bd3.doubleValue();
            String trs = Double.toString(trd);
            double t1y = trd * 12.0;
            BigDecimal bd13 = new BigDecimal(Double.toString(t1y));
            bd13 = bd13.setScale(2, RoundingMode.HALF_UP);
            ty = bd13.doubleValue();
            
            ml = (10.0/100.0)*b_sal;
            BigDecimal bd4 = new BigDecimal(Double.toString(ml));
            bd4 = bd4.setScale(2, RoundingMode.HALF_UP);
            double mld = bd4.doubleValue();
            String mls = Double.toString(mld);
            double ml1y = mld * 12.0;
            BigDecimal bd14 = new BigDecimal(Double.toString(ml1y));
            bd14 = bd14.setScale(2, RoundingMode.HALF_UP);
            mly = bd14.doubleValue();
            
            en = (5.0/100.0)*b_sal;
            BigDecimal bd5 = new BigDecimal(Double.toString(en));
            bd5 = bd5.setScale(2, RoundingMode.HALF_UP);
            double end = bd5.doubleValue();
            String ens = Double.toString(end);
            double en1y = end * 12.0;
            BigDecimal bd15 = new BigDecimal(Double.toString(en1y));
            bd15 = bd15.setScale(2, RoundingMode.HALF_UP);
            eny = bd15.doubleValue();
            
            ul = (5.0/100.0)*b_sal;
            BigDecimal bd6 = new BigDecimal(Double.toString(ul));
            bd6 = bd6.setScale(2, RoundingMode.HALF_UP);
            double uld = bd6.doubleValue();
            String uls = Double.toString(uld);
            double ul1y = uld * 12.0;
            BigDecimal bd16 = new BigDecimal(Double.toString(ul1y));
            bd16 = bd16.setScale(2, RoundingMode.HALF_UP);
            uly = bd16.doubleValue();
            
        
            //System.out.println(bs);
            
            txtBasic.setText(bss);
            txtHouse.setText(hss);
            txtTrans.setText(trs);
            txtMeal.setText(mls);
            txtEnter.setText(ens);
            txtUtility.setText(uls);
            
            double ttl = b_sal + ttl_A;
            double gi1y= b_sal2 + othy;
            BigDecimal bd18 = new BigDecimal(Double.toString(gi1y));
            bd18 = bd18.setScale(2, RoundingMode.HALF_UP);
            giy = bd18.doubleValue();
            
            String ttl_M = Double.toString(ttl);
            txtGross.setText(ttl_M);
            
        
        }
        //ss = 
        
    }//GEN-LAST:event_btnCalActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
           
        String txt=txtSearch.getText();
        if(txt.equals(""))
            JOptionPane.showMessageDialog(this,"field is empty, type in something to search!");

        else
        {
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
                Connection connect = DriverManager.getConnection(url);
                Statement st = connect.createStatement();
                rs = st.executeQuery("select * from EMP_Table where EmployeeID LIKE '%"+txtSearch.getText()+"%' or Surname LIKE '%"+txtSearch.getText()+"%'");
            
               // rs=stmt.executeQuery(query); 
                while(rs.next())
                {
 
                    txtID.setText(rs.getString("EmployeeID"));
                    txtSurname.setText(rs.getString("Surname"));
                    txtFirst.setText(rs.getString("First_name"));
                    txtMiddle.setText(rs.getString("Middle_name"));
                    txtSalary.setText(rs.getString("Basic_Salary"));
                    txtDPT.setText(rs.getString("Department"));
                    
                }
                
                connect.close();
                         
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }   
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAdd_Student1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_Student1ActionPerformed
        // TODO add your handling code here:
            
        if(txtBasic.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute"); 
        else if(txtHouse.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute");
        else if(txtTrans.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute");
        else if(txtMeal.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute");
        else if(txtEnter.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute");
        else if(txtUtility.getText().equals(""))
            JOptionPane.showMessageDialog(this,"allowance fields can not be empty, click compute");  
        else if(txtID.getText().equals(""))
            JOptionPane.showMessageDialog(this,"there is no available data to save!");
        else
        {
           
        try{
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            //String sql = "insert into Book_Table" + "(Title, Author, Edition, Quantity, ISBN, Publisher, Yr_Of_Public)" + "Values(?,?,?,?,?,?,?)"  + " (SELECT * FROM Subject_Table WHERE Subject_ID = ?)" + " (SELECT * FROM Shelf_Table WHERE Shelf_ID= ?)";
            String sql = "insert into Allowance_Table" + "(EmployeeID, Basic, Housing, Transport, Meal, Entertainment, Utility, Others, Gross_Income, Basic_Yr, Housing_Yr, Transport_Yr, Meal_Yr, Entertainment_Yr, Utility_Yr, Others_Yr, Gross_Income_Yr)" + "Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            Statement st1 = connect.createStatement();
            ResultSet rs1 = st1.executeQuery("SELECT * FROM EMP_table WHERE EmployeeID = '"+ txtID.getText() +"'");

            Statement st2 = connect.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from Allow_vw_Table WHERE EmployeeID = '"+ txtID.getText() +"'");
            
            PreparedStatement pst = connect.prepareStatement(sql);
            
            while(rs1.next()){
                        dd =rs1.getString("EmployeeID");
                        pst.setString(1, dd);
                    }
            pst.setString(2, txtBasic.getText());
            pst.setString(3, txtHouse.getText());
            pst.setString(4, txtTrans.getText());
            pst.setString(5, txtMeal.getText());
            pst.setString(6, txtEnter.getText());
            pst.setString(7, txtUtility.getText());
            pst.setString(8, txtOthers.getText());
            pst.setString(9, txtGross.getText());
            pst.setString(10, Double.toString(bsy));
            pst.setString(11, Double.toString(hsy));
            pst.setString(12, Double.toString(ty));
            pst.setString(13, Double.toString(mly));
            pst.setString(14, Double.toString(eny));
            pst.setString(15, Double.toString(uly));
            pst.setString(16, Double.toString(othy));
            pst.setString(17, Double.toString(giy));
              
            if(rs2.next()){
                
                String sql2 = "update Allowance_Table set EmployeeID = ?, Basic = ?,Housing = ?,Transport = ?, Meal = ?,Entertainment = ?,Utility = ?, Others = ?,Gross_Income = ? , Basic_Yr = ?,Housing_Yr = ?,Transport_Yr = ?, Meal_Yr = ?,Entertainment_Yr = ?,Utility_Yr = ?, Others_Yr = ?,Gross_Income_Yr = ? where EmployeeID = '"+ txtID.getText() +"'";
             
                //Statement st3 = connect.createStatement();
                ResultSet rs3 = st1.executeQuery("SELECT * FROM EMP_table WHERE EmployeeID = '"+ txtID.getText() +"'");

                PreparedStatement pst2 = connect.prepareStatement(sql2);

                while(rs3.next()){
                            dd =rs3.getString("EmployeeID");
                            pst2.setString(1, dd);
                        }
                pst2.setString(2, txtBasic.getText());
                pst2.setString(3, txtHouse.getText());
                pst2.setString(4, txtTrans.getText());
                pst2.setString(5, txtMeal.getText());
                pst2.setString(6, txtEnter.getText());
                pst2.setString(7, txtUtility.getText());
                pst2.setString(8, txtOthers.getText());
                pst2.setString(9, txtGross.getText());
                pst2.setString(10, Double.toString(bsy));
                pst2.setString(11, Double.toString(hsy));
                pst2.setString(12, Double.toString(ty));
                pst2.setString(13, Double.toString(mly));
                pst2.setString(14, Double.toString(eny));
                pst2.setString(15, Double.toString(uly));
                pst2.setString(16, Double.toString(othy));
                pst2.setString(17, Double.toString(giy));
                
                pst2.executeUpdate();
                JOptionPane.showMessageDialog(this,"Allowance updated for " + txtSurname.getText() + " " + txtSurname.getText());
                

                DefaultTableModel model=(DefaultTableModel)table.getModel();
                model.setRowCount(0);
                Statement st = connect.createStatement();
                rs = st.executeQuery("select * from Allow_vw_Table order by EmployeeID ASC");

                    while(rs.next())
                    {
                        em1=rs.getString("EmployeeID");
                        em2=rs.getString("Surname") + " " + rs.getString("First_name");
                        em3=rs.getString("Basic");
                        em4=rs.getString("Housing");
                        em5=rs.getString("Transport");
                        em6=rs.getString("Meal");
                        em7=rs.getString("Entertainment");
                        em8=rs.getString("Utility");
                        em9=rs.getString("Others");
                        em10=rs.getString("Gross_Income");
                        Object[] row = {em1,em2,em3,em4,em5,em6,em7,em8,em9,em10};
                        model.addRow(row);
                    }
                
                
            }else{
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Allowance added for " + txtSurname.getText() + " " + txtSurname.getText());


                DefaultTableModel model=(DefaultTableModel)table.getModel();
                model.setRowCount(0);
                Statement st = connect.createStatement();
                rs = st.executeQuery("select * from Allow_vw_Table order by EmployeeID ASC");

                    while(rs.next())
                    {
                        em1=rs.getString("EmployeeID");
                        em2=rs.getString("Surname") + " " + rs.getString("First_name");
                        em3=rs.getString("Basic");
                        em4=rs.getString("Housing");
                        em5=rs.getString("Transport");
                        em6=rs.getString("Meal");
                        em7=rs.getString("Entertainment");
                        em8=rs.getString("Utility");
                        em9=rs.getString("Others");
                        em10=rs.getString("Gross_Income");
                        Object[] row = {em1,em2,em3,em4,em5,em6,em7,em8,em9,em10};
                        model.addRow(row);
                    }
                
        
            }
          
        
        }
        catch(SQLException e)
            
            {
 
 
    System.out.println("Could not retrieve database metadata " + e.getMessage());
 
    }catch (ClassNotFoundException ex) {
                Logger.getLogger(EmpMGT.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
    }//GEN-LAST:event_btnAdd_Student1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllowancePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd_Student1;
    public static javax.swing.JButton btnCal;
    public static javax.swing.JButton btnSearch;
    public static javax.swing.JButton btnUpdate1;
    public static javax.swing.JButton btnUpdate3;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JPanel std_panel;
    private javax.swing.JTable table;
    public static javax.swing.JTextField txtBasic;
    public static javax.swing.JTextField txtDPT;
    public static javax.swing.JTextField txtEnter;
    public static javax.swing.JTextField txtFirst;
    public static javax.swing.JTextField txtGross;
    public static javax.swing.JTextField txtHouse;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtMeal;
    public static javax.swing.JTextField txtMiddle;
    public static javax.swing.JTextField txtOthers;
    public static javax.swing.JTextField txtSalary;
    public static javax.swing.JTextField txtSearch;
    public static javax.swing.JTextField txtSurname;
    public static javax.swing.JTextField txtTrans;
    public static javax.swing.JTextField txtUtility;
    // End of variables declaration//GEN-END:variables
}
