package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class DeductionPage extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    String dd, dd1, dd2;
    String fn, ln, mn, ll, pg, dp, yr, fc;
    String ns, mt, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, t1, t2, t3, t4, rm;
    double Anu_PA, Anu_P;
    
    
    int rowCount = -1;
    public DeductionPage() {
        initComponents();
        
          
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
   
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        std_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFirstname4 = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnAdd_Student1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtPENS = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtTFP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtTXI = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPAYE = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFirstname13 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtFirstname14 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtFirstname15 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtFirstname16 = new javax.swing.JTextField();
        txtFirstname17 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        txtMiddle = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtDPT = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnAdd_Student = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1160, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_panel.setBackground(new java.awt.Color(102, 102, 102));
        std_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        std_panel.setMinimumSize(new java.awt.Dimension(932, 611));
        std_panel.setPreferredSize(new java.awt.Dimension(932, 611));
        std_panel.setRequestFocusEnabled(false);
        std_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First name : ");
        std_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Middle name : ");
        std_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 30));

        jLabel11.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department : ");
        std_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 30));

        txtFirstname4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFirstname4.setEnabled(false);
        txtFirstname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname4ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 230, 30));

        btnUpdate1.setBackground(new java.awt.Color(163, 192, 192));
        btnUpdate1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(219, 6, 6));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/clr.png"))); // NOI18N
        btnUpdate1.setText("Clear");
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, 160, 40));

        jLabel19.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Surname : ");
        std_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 30));

        btnAdd_Student1.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student1.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/save.png"))); // NOI18N
        btnAdd_Student1.setText("Add Record");
        btnAdd_Student1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnAdd_Student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 160, 40));

        jLabel29.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Employee ID : ");
        std_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        btnCal.setBackground(new java.awt.Color(163, 192, 192));
        btnCal.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnCal.setForeground(new java.awt.Color(16, 107, 35));
        btnCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/cal.png"))); // NOI18N
        btnCal.setText("Calculate");
        btnCal.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });
        std_panel.add(btnCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 160, 40));

        jLabel18.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NHF :");
        std_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 80, 30));

        jLabel23.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PERS. ALLOW (Earned Income *20%+200,000) : ");
        std_panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 380, 30));

        txtPA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPA.setEnabled(false);
        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        std_panel.add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 200, 30));

        jLabel10.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("STATUTORY");
        std_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 30));

        jLabel12.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 235, 235));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("kindly update employee gross income with deductions");
        std_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 570, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        std_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 10, 200));
        std_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 1040, 10));

        jLabel20.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PENSION :");
        std_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 90, 30));

        txtPENS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPENS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPENS.setEnabled(false);
        txtPENS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPENSActionPerformed(evt);
            }
        });
        std_panel.add(txtPENS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 230, 30));

        jLabel30.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("- (Annually)");
        std_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 90, 30));

        jLabel31.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("(8% of Basic + Housing + Transport)");
        std_panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 280, 30));

        txtTFP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTFP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTFP.setEnabled(false);
        txtTFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTFPActionPerformed(evt);
            }
        });
        std_panel.add(txtTFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 170, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TAX FREE PAY");
        std_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 140, 30));

        jLabel32.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("- (by %)");
        std_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 80, 30));

        txtTXI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTXI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTXI.setEnabled(false);
        txtTXI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTXIActionPerformed(evt);
            }
        });
        std_panel.add(txtTXI, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 200, 30));

        jLabel25.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("TAXABLE INCOME");
        std_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 170, 30));

        txtPAYE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPAYE.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPAYE.setEnabled(false);
        txtPAYE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAYEActionPerformed(evt);
            }
        });
        std_panel.add(txtPAYE, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 180, 30));

        jLabel33.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("PAYE");
        std_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 70, 30));

        jLabel35.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("(2.5%  of Basic)");
        std_panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 120, 30));

        jLabel13.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("TAXATION");
        std_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 90, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("NHF :");
        std_panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 80, 30));

        txtFirstname13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname13.setEnabled(false);
        txtFirstname13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname13ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 170, 30));

        jLabel36.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("PENSION :");
        std_panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 30));

        txtFirstname14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname14.setEnabled(false);
        txtFirstname14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname14ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 170, 30));

        jLabel37.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("(2.5%  of Basic)");
        std_panel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 120, 30));

        jLabel38.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("(8% of B + H + T) - Employee");
        std_panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 230, 30));

        jLabel39.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("(10% of B + H + T) - Employer");
        std_panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 230, 30));

        txtFirstname15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname15.setEnabled(false);
        txtFirstname15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname15ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 170, 30));

        jLabel40.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("PENSION :");
        std_panel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 90, 30));

        jLabel14.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("OTHER DEDUCTIONS");
        std_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 180, 30));

        jLabel24.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Car Loan Repayment");
        std_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 190, 30));

        txtFirstname16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname16.setEnabled(false);
        txtFirstname16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname16ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 170, 30));

        txtFirstname17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstname17.setEnabled(false);
        txtFirstname17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname17ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 170, 30));

        jLabel27.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("I. O. U");
        std_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 110, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        std_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 10, 350));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        std_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 10, 200));

        jLabel26.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Salary : ");
        std_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 30));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setEnabled(false);
        std_panel.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 250, 30));

        txtSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSurname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSurname.setEnabled(false);
        std_panel.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, 30));

        txtFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirst.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFirst.setEnabled(false);
        std_panel.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, 30));

        txtMiddle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMiddle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMiddle.setEnabled(false);
        std_panel.add(txtMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, 30));

        txtSalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSalary.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSalary.setEnabled(false);
        std_panel.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 250, 30));

        txtDPT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDPT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDPT.setEnabled(false);
        txtDPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPTActionPerformed(evt);
            }
        });
        std_panel.add(txtDPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 250, 30));

        jPanel3.add(std_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1120, 630));

        jPanel4.setBackground(new java.awt.Color(245, 245, 246));

        btnUpdate3.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate3.setText("HOME");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 80, 30));

        jLabel34.setBackground(new java.awt.Color(0, 204, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/logo.png"))); // NOI18N
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, -1, 70));

        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Deduction");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 30));

        jPanel5.setBackground(new java.awt.Color(245, 245, 246));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Perpetua", 2, 18)); // NOI18N
        jLabel28.setText("Search by ID or Surname : ");

        btnAdd_Student.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd_Student.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/sec.png"))); // NOI18N
        btnAdd_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_StudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd_Student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 460, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname4ActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
        MainForm rs = new MainForm();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void txtPENSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPENSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPENSActionPerformed

    private void txtTFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTFPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTFPActionPerformed

    private void txtTXIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTXIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTXIActionPerformed

    private void txtPAYEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAYEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAYEActionPerformed

    private void txtFirstname13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname13ActionPerformed

    private void txtFirstname14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname14ActionPerformed

    private void txtFirstname15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname15ActionPerformed

    private void txtFirstname16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname16ActionPerformed

    private void txtFirstname17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname17ActionPerformed

    private void btnAdd_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_StudentActionPerformed
        // TODO add your handling code here:
             
        String txt=txtSearch.getText();
        if(txt.equals(""))
            
            JOptionPane.showMessageDialog(this,"field is empty, type in something to search!");

        else
        {
            try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
                Connection connect = DriverManager.getConnection(url);
                Statement st = connect.createStatement();
                rs = st.executeQuery("select * from EMP_Table where EmployeeID LIKE '%"+txtSearch.getText()+"%' or Surname LIKE '%"+txtSearch.getText()+"%'");
            
               // rs=stmt.executeQuery(query); 
                while(rs.next())
                {
 
                    txtID.setText(rs.getString("EmployeeID"));
                    txtSurname.setText(rs.getString("Surname"));
                    txtFirst.setText(rs.getString("First_name"));
                    txtMiddle.setText(rs.getString("Middle_name"));
                    txtSalary.setText(rs.getString("Basic_Salary"));
                    txtDPT.setText(rs.getString("Department"));
                    
                }
                
                connect.close();
                         
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }   
    }//GEN-LAST:event_btnAdd_StudentActionPerformed

    private void txtDPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPTActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        
        if(!txtSalary.getText().equals("")){
             try
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
                Connection connect = DriverManager.getConnection(url);
                Statement st = connect.createStatement();
                rs = st.executeQuery("select * from Allow_vw_Table where EmployeeID = '"+txtID.getText()+"'");
            
               // rs=stmt.executeQuery(query); 
                while(rs.next())
                {
 
                    String S_PA = rs.getString("Gross_Income_Yr");
                    Anu_PA = Double.parseDouble(S_PA);
                    double _PA = (((20.0/100.0) * Anu_PA) + 200000.0);
                    
                    BigDecimal bd = new BigDecimal(Double.toString(_PA));
                    bd = bd.setScale(2, RoundingMode.HALF_UP);
                    double pa = bd.doubleValue();
                    String _PAS = Double.toString(pa);
                    txtPA.setText(_PAS);
                    
                    
                    String S_BA = rs.getString("Basic_Yr");
                    double _B = Double.parseDouble(S_BA);
                    
                    String S_HA = rs.getString("Housing_Yr");
                    double _H = Double.parseDouble(S_HA);
                    
                    String S_TA = rs.getString("Transport_Yr");
                    double _T = Double.parseDouble(S_TA);
                    
                    //PENSION
                    double _P = ((8.0/100.0) * (_B + _H + _T));
                    BigDecimal bds = new BigDecimal(Double.toString(_P));
                    bds = bds.setScale(2, RoundingMode.HALF_UP);
                    double ps = bds.doubleValue();
                    String _PP = Double.toString(ps);
                    txtPENS.setText(_PP);
                    
                    //TAX FREE PAY
                    double tfp = pa + ps;
                    BigDecimal tt = new BigDecimal(Double.toString(tfp));
                    tt = tt.setScale(2, RoundingMode.HALF_UP);
                    double tps = tt.doubleValue();
                    String _TFP = Double.toString(tps);
                    txtTFP.setText(_TFP);
                    
                    //TAXABLE s
                    double TaxInc = Anu_PA - tps;
                    BigDecimal txt = new BigDecimal(Double.toString(TaxInc));
                    txt = txt.setScale(2, RoundingMode.HALF_UP);
                    double txi = txt.doubleValue();
                    String _TXP = Double.toString(txi);
                    txtTXI.setText(_TXP);
                    
                    if(txi < 300000.0){
                        double paye = (7.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }else if(txi == 300000.0){
                        double paye = (11.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }else if(txi < 500000.0){
                        double paye = (15.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }else if(txi == 500000.0){
                        double paye = (19.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }else if(txi == 1600000.0){
                        double paye = (21.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }else if(txi == 3200000.0){
                        double paye = (24.0/100.0) * txi;
                        String _PAYE = Double.toString(paye);
                        txtPAYE.setText(_PAYE);
                        
                    }
                }
                          
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_btnCalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeductionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd_Student;
    public static javax.swing.JButton btnAdd_Student1;
    public static javax.swing.JButton btnCal;
    public static javax.swing.JButton btnUpdate1;
    public static javax.swing.JButton btnUpdate3;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JPanel std_panel;
    public static javax.swing.JTextField txtDPT;
    public static javax.swing.JTextField txtFirst;
    public static javax.swing.JTextField txtFirstname13;
    public static javax.swing.JTextField txtFirstname14;
    public static javax.swing.JTextField txtFirstname15;
    public static javax.swing.JTextField txtFirstname16;
    public static javax.swing.JTextField txtFirstname17;
    public static javax.swing.JTextField txtFirstname4;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtMiddle;
    public static javax.swing.JTextField txtPA;
    public static javax.swing.JTextField txtPAYE;
    public static javax.swing.JTextField txtPENS;
    public static javax.swing.JTextField txtSalary;
    public static javax.swing.JTextField txtSearch;
    public static javax.swing.JTextField txtSurname;
    public static javax.swing.JTextField txtTFP;
    public static javax.swing.JTextField txtTXI;
    // End of variables declaration//GEN-END:variables
}
