package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class EmpMGT extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    String s, mt, d1, d2, gender;
    String filename;
    byte[] p_img = null;
    
    
    int rowCount = -1;
    public EmpMGT() {
        initComponents();
        
          
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
   
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        std_panel = new javax.swing.JPanel();
        btnAdd_Student = new javax.swing.JButton();
        txtSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnGen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMidname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbFemale = new javax.swing.JRadioButton();
        rbMale = new javax.swing.JRadioButton();
        jdcDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtDepart = new javax.swing.JTextField();
        txtDesign = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_panel.setBackground(new java.awt.Color(255, 255, 255));
        std_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        std_panel.setMinimumSize(new java.awt.Dimension(932, 611));
        std_panel.setPreferredSize(new java.awt.Dimension(932, 611));
        std_panel.setRequestFocusEnabled(false);
        std_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd_Student.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/save.png"))); // NOI18N
        btnAdd_Student.setText("Add Record");
        btnAdd_Student.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAdd_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_StudentActionPerformed(evt);
            }
        });
        std_panel.add(btnAdd_Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 160, 40));

        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, 30));

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("*");
        std_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 20, 20));

        jLabel17.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("if none ?");
        std_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 20));

        txtEmpID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, 30));

        jLabel28.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel28.setText("Employee ID : ");
        std_panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        btnGen.setBackground(new java.awt.Color(51, 51, 51));
        btnGen.setForeground(new java.awt.Color(255, 255, 255));
        btnGen.setText("Generate");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });
        std_panel.add(btnGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel6.setText("First name : ");
        std_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        txtFirstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 250, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel7.setText("Middle name : ");
        std_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel8.setText("Date of Birth : ");
        std_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 30));

        txtMidname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtMidname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, 30));

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel9.setText("Gender : ");
        std_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 30));

        rbFemale.setBackground(new java.awt.Color(255, 255, 255));
        b1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });
        std_panel.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        rbMale.setBackground(new java.awt.Color(255, 255, 255));
        b1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        std_panel.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        std_panel.add(jdcDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 260, 30));

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setText("Department : ");
        std_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 110, 30));

        txtDepart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartActionPerformed(evt);
            }
        });
        std_panel.add(txtDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 260, 30));

        txtDesign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 260, 30));

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel12.setText("Designation : ");
        std_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 110, 30));

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 260, 30));

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel13.setText("Status : ");
        std_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 110, 30));

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel14.setText("Date Employed : ");
        std_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 120, 30));

        jLabel15.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel15.setText("Email : ");
        std_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 250, 30));

        txtContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 250, 30));

        jLabel16.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel16.setText("Contact : ");
        std_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 30));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 250, 30));

        jLabel18.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel18.setText("Address Line : ");
        std_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 110, 30));

        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 260, 30));

        jLabel20.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel20.setText("Basic Salary : ");
        std_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, 30));

        txtJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        std_panel.add(txtJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 260, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setText("Job Title : ");
        std_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 120, 30));

        jPanel1.setBackground(new java.awt.Color(250, 249, 249));

        lblImg.setForeground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/emp3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        std_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 210, 200));

        btnUpdate1.setBackground(new java.awt.Color(163, 192, 192));
        btnUpdate1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(219, 6, 6));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/clr.png"))); // NOI18N
        btnUpdate1.setText("Clear");
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 160, 40));

        jLabel19.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel19.setText("Surname : ");
        std_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        jLabel22.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("*");
        std_panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 20, 20));

        jLabel23.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("*");
        std_panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 20, 20));

        jLabel24.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("*");
        std_panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 20, 20));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("*");
        std_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 20, 20));

        jLabel26.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("*");
        std_panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 20, 20));

        jLabel27.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("*");
        std_panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 20, 20));

        jLabel29.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("*");
        std_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 20, 20));

        jLabel30.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("*");
        std_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 20, 20));

        jLabel31.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("*");
        std_panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 20, 20));

        jLabel32.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("*");
        std_panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 20, 20));

        jLabel33.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("*");
        std_panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 20, 20));

        btnImage.setBackground(new java.awt.Color(102, 102, 102));
        btnImage.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnImage.setForeground(new java.awt.Color(255, 255, 255));
        btnImage.setText("Upload Image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        std_panel.add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 130, 30));

        jdcDOB.setDateFormatString("d MMM, yyyy");
        std_panel.add(jdcDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 250, 30));

        jPanel3.add(std_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1100, 590));

        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Employee Details");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 30));

        jPanel4.setBackground(new java.awt.Color(245, 245, 246));

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("VIEW EMPLOYEE");

        btnHome.setBackground(new java.awt.Color(0, 102, 102));
        btnHome.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnUpdate))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 270, 30));

        jLabel34.setBackground(new java.awt.Color(0, 204, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/logo.png"))); // NOI18N
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, 120, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_rbMaleActionPerformed

    private void txtDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        MainForm rs = new MainForm();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAdd_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_StudentActionPerformed
        // TODO add your handling code here:
            
        if(txtEmpID.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Employee ID is requied"); 
        else if(txtSurname.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Surname is requied");
        else if(txtFirstname.getText().equals(""))
            JOptionPane.showMessageDialog(this,"First name is requied");
        else if(txtMidname.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Middle name is requied");
        else if(txtEmail.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Email is requied");
        else if(txtContact.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Contact is requied");  
        else if(txtAddress.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Address is required");
        else if(txtDepart.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Department is required"); 
        else if(txtDesign.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Designation is required");
        else if(txtSalary.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Basic Salary is required");
        else
        {
           
        try{
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            //String sql = "insert into Book_Table" + "(Title, Author, Edition, Quantity, ISBN, Publisher, Yr_Of_Public)" + "Values(?,?,?,?,?,?,?)"  + " (SELECT * FROM Subject_Table WHERE Subject_ID = ?)" + " (SELECT * FROM Shelf_Table WHERE Shelf_ID= ?)";
            String sql = "insert into EMP_table" + "(EmployeeID, Surname, First_name, Middle_name, DOB, Gender, Email, Contact, Address, Department, Designation, Status, Date_Employed, Basic_Salary, Job_title, ImageURL)" + "Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            /*
                InputStream ss = new FileInputStream(new File(s));
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for(int readNum; (readNum=ss.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
            }
                p_img = bos.toByteArray();
            */
            if(rbMale.isSelected()){
                gender = "Male";
            }else if(rbFemale.isSelected()){
                gender = "Female";
            }
            
            d1  = ((JTextField)jdcDOB.getDateEditor().getUiComponent()).getText();
            d2  = ((JTextField)jdcDate.getDateEditor().getUiComponent()).getText();
            
            PreparedStatement pst = connect.prepareStatement(sql);
            pst.setString(1, txtEmpID.getText());
            pst.setString(2, txtSurname.getText());
            pst.setString(3, txtFirstname.getText());
            pst.setString(4, txtMidname.getText());
            pst.setString(5, d1);
            pst.setString(6, gender);
            pst.setString(7, txtEmail.getText());
            pst.setString(8, txtContact.getText());
            pst.setString(9, txtAddress.getText());
            pst.setString(10, txtDepart.getText());
            pst.setString(11, txtDesign.getText());
            pst.setString(12, txtStatus.getText());
            pst.setString(13, txtStatus.getText());
            pst.setString(14, txtSalary.getText());
            pst.setString(15, txtJob.getText());
            pst.setBytes(16, p_img);
              
            pst.executeUpdate();
            

            JOptionPane.showMessageDialog(this,"New Employee Added to The System");

        
        }
        catch(SQLException e)
            
            {
 
 
    System.out.println("Could not retrieve database metadata " + e.getMessage());
 
    }catch (ClassNotFoundException ex) {
                Logger.getLogger(EmpMGT.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
       
    }//GEN-LAST:event_btnAdd_StudentActionPerformed

    
    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH));
        lblImg.setIcon(imageIcon);
        
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
            
            }
            p_img=bos.toByteArray();
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        
        }
        
        
        /*
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filt = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filt);
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblImg.setIcon(ResizeImage(path));
            s = path;
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(this,"No Selected File");
            
        }*/
        
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        // TODO add your handling code here:
           
        if(txtEmpID.getText().isEmpty()){
        
          Random rand = new Random(); 
  
            // Generate random integers in range 0 to 999 
            int rand_int1 = rand.nextInt(1000); 


            String firstWord = "TU/P/";
                firstWord = firstWord + rand_int1; 
                txtEmpID.setText(firstWord);
            
        }else{}
    }//GEN-LAST:event_btnGenActionPerformed

    public ImageIcon ResizeImage(String ImagePath){
        
        ImageIcon Myimg = new ImageIcon(ImagePath);
        Image img = Myimg.getImage();
        Image newImg = img.getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(newImg);
        return img2;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpMGT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup b1;
    public static javax.swing.JButton btnAdd_Student;
    private javax.swing.JButton btnGen;
    public static javax.swing.JButton btnHome;
    public static javax.swing.JButton btnImage;
    public static javax.swing.JButton btnUpdate;
    public static javax.swing.JButton btnUpdate1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private com.toedter.calendar.JDateChooser jdcDate;
    private javax.swing.JLabel lblImg;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    public static javax.swing.JPanel std_panel;
    public static javax.swing.JTextField txtAddress;
    public static javax.swing.JTextField txtContact;
    public static javax.swing.JTextField txtDepart;
    public static javax.swing.JTextField txtDesign;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEmpID;
    public static javax.swing.JTextField txtFirstname;
    public static javax.swing.JTextField txtJob;
    public static javax.swing.JTextField txtMidname;
    public static javax.swing.JTextField txtSalary;
    public static javax.swing.JTextField txtStatus;
    public static javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
