package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tunani
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
            //This for on enter key function//login
        btnLogin.registerKeyboardAction(btnLogin.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_IN_FOCUSED_WINDOW);
 
        btnLogin.registerKeyboardAction(btnLogin.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        //jLabel4.setFont(new Font("Sabon", Font.PLAIN, 20));
       // SetImageSize(6);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpass1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        juser1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblSlide_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1033, 718));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 462));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/b.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 170, 90));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpass1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jpass1.setText("Enter password");
        jpass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpass1FocusLost(evt);
            }
        });
        jpass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpass1MouseClicked(evt);
            }
        });
        jpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpass1ActionPerformed(evt);
            }
        });
        jPanel6.add(jpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/pass_img.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, 40));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 180, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(239, 240, 230));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SYSTEM");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 280, 70));

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kindly enter your username and password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 320, 30));

        jLabel9.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 150, 20));

        jLabel13.setFont(new java.awt.Font("Segoe Condensed", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(228, 226, 226));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Designed by Ayejafo Tunde");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, 140, 20));

        juser1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        juser1.setForeground(new java.awt.Color(102, 102, 102));
        juser1.setText("Enter username");
        juser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                juser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                juser1FocusLost(evt);
            }
        });
        juser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juser1MouseClicked(evt);
            }
        });
        juser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juser1ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/user_img.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(juser1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(juser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 280, 40));

        jLabel14.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 150, 20));

        lblSlide_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlide_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/payroll.jpg"))); // NOI18N
        lblSlide_Login.setPreferredSize(new java.awt.Dimension(1049, 749));
        jPanel1.add(lblSlide_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass1FocusGained
        // TODO add your handling code here:
        //jpass1.setText("");
        if( jpass1.getText().equals("Enter password")){
            jpass1.setText("");
        }
        jpass1.setForeground(Color.BLACK);
        jpass1.setFont(new Font("TimesRoman", Font.PLAIN, 14));

        jpass1.setEchoChar('*');
    }//GEN-LAST:event_jpass1FocusGained

    private void jpass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpass1FocusLost
        // TODO add your handling code here:
        if( jpass1.getText().equals("")){
            jpass1.setText("Enter password");
        }

    }//GEN-LAST:event_jpass1FocusLost

    private void jpass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpass1MouseClicked
        // TODO add your handling code here:

        //juser1.setText("");
        jpass1.setText("");
    }//GEN-LAST:event_jpass1MouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433; database=Payroll_DB; user=sa; password=Tunani14real;";
            Connection connect = DriverManager.getConnection(url);
            String sql = "select * from Login_Table where Username = ? and Password = ?";
            // String sql2 = "select * from User_vw_Table where User_Name = ? and Password = ?";
            PreparedStatement pst = connect.prepareStatement(sql);
            // PreparedStatement pst2 = connect.prepareStatement(sql2);

            //pst.setString(1, Name);
            pst.setString(1, juser1.getText());
            pst.setString(2, jpass1.getText());

            ResultSet rs = pst.executeQuery();

            // pst2.setString(1, juser1.getText());
            // pst2.setString(2, jpass1.getText());
            // ResultSet rs2 = pst2.executeQuery();

            if(rs.next()){
                if(juser1.getText().equals(rs.getString("Username")) && jpass1.getText().equals(rs.getString("Password"))){
                    String get = rs.getString("Lastname");
                    JOptionPane.showMessageDialog(null,  "Sucessful Login!!!", "Sucess", JOptionPane.INFORMATION_MESSAGE);
                    juser1.setText("");
                    jpass1.setText("");

                    MainForm home = new MainForm();
                    MainForm.F_user.setText(get);
                    home.setVisible(true);
                    this.dispose();
                            
                }
                else{

                    JOptionPane.showMessageDialog(null,  "incorrect username or password", "Failed", JOptionPane.INFORMATION_MESSAGE);

                    juser1.setText("Enter username");
                    jpass1.setText("Enter password");

                }

            }else{

                JOptionPane.showMessageDialog(null,  "incorrect username or password", "Failed", JOptionPane.INFORMATION_MESSAGE);

                juser1.setText("Enter username");
                jpass1.setText("Enter password");

            }

            connect.close();

        }catch(Exception error){

            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void juser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser1FocusGained
        // TODO add your handling code here:

        if(juser1.getText().equals("Enter username")){
            juser1.setText("");
        }
        juser1.setForeground(Color.BLACK);
        juser1.setFont(new Font("TimesRoman", Font.PLAIN, 14));
    }//GEN-LAST:event_juser1FocusGained

    private void juser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser1FocusLost
        // TODO add your handling code here:
        if(juser1.getText().equals("")){
            juser1.setText("Enter username");
        }

    }//GEN-LAST:event_juser1FocusLost

    private void juser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juser1MouseClicked
        // TODO add your handling code here:

        juser1.setText("");
        //jpass1.setText("");
    }//GEN-LAST:event_juser1MouseClicked

    private void jpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpass1ActionPerformed

    private void juser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JTextField juser1;
    private javax.swing.JLabel lblSlide_Login;
    // End of variables declaration//GEN-END:variables
}
