package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.GregorianCalendar;

public class MainForm extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    String dd, dd1, dd2;
    String fn, ln, mn, ll, pg, dp, yr, fc;
    String ns, mt, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, t1, t2, t3, t4, rm;
    
    
    int rowCount = -1;
    public MainForm() {
        initComponents();
        
          
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
       
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
      
        DateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
        DateFormat dateFormat2 = new SimpleDateFormat("HH:mm:ss");
        //get current date time with Date()
        Date date = new Date();
        lblTime.setText(dateFormat1.format(date));
        
        //get current date time with Calendar()
        Calendar cal = Calendar.getInstance();
        lblTime1.setText(dateFormat2.format(cal.getTime()));
        
       /*
        //Greggorian Calendar
        Calendar cal1 = new GregorianCalendar();
        int month = cal1.get(Calendar.MONTH);
        int year = cal1.get(Calendar.YEAR);
        int day = cal1.get(Calendar.DAY_OF_MONTH);
        
        lblTime.setText(day + "/" + (month + 1) + "/" + year);
        
        int sec = cal1.get(Calendar.SECOND);
        int min = cal1.get(Calendar.MINUTE);
        int hr = cal1.get(Calendar.HOUR);
        
        lblTime1.setText(hr + ":" + (min) + ":" + sec);
        */
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        F_user = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEmp = new javax.swing.JButton();
        btnUpSal = new javax.swing.JButton();
        F_user3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDed = new javax.swing.JButton();
        btnAllow = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnRep = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSlide_Login1 = new javax.swing.JLabel();
        lblSlide_Login = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 9, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        F_user.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        F_user.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(F_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 160, 41));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("TU PAYROLL DASHBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        lblTime.setBackground(new java.awt.Color(38, 17, 87));
        lblTime.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 140, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/shutdown.png"))); // NOI18N
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 30));

        btnEmp.setBackground(new java.awt.Color(241, 247, 247));
        btnEmp.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnEmp.setForeground(new java.awt.Color(114, 25, 202));
        btnEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/emp4.png"))); // NOI18N
        btnEmp.setText("Employee MGT");
        btnEmp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 250, 80));

        btnUpSal.setBackground(new java.awt.Color(241, 247, 247));
        btnUpSal.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnUpSal.setForeground(new java.awt.Color(234, 14, 42));
        btnUpSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/sal2.png"))); // NOI18N
        btnUpSal.setText("  Update Salary");
        btnUpSal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpSalActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 240, 80));

        F_user3.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        F_user3.setForeground(new java.awt.Color(249, 247, 247));
        F_user3.setText("Welcome! ");
        jPanel1.add(F_user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 110, 41));

        jLabel7.setBackground(new java.awt.Color(0, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/b.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 140, 70));

        btnDed.setBackground(new java.awt.Color(241, 247, 247));
        btnDed.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnDed.setForeground(new java.awt.Color(0, 102, 102));
        btnDed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/ded.png"))); // NOI18N
        btnDed.setText("  Deduction");
        btnDed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDedActionPerformed(evt);
            }
        });
        jPanel1.add(btnDed, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 250, 80));

        btnAllow.setBackground(new java.awt.Color(241, 247, 247));
        btnAllow.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnAllow.setForeground(new java.awt.Color(51, 153, 0));
        btnAllow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/alw2.png"))); // NOI18N
        btnAllow.setText("  Allowance");
        btnAllow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAllow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowActionPerformed(evt);
            }
        });
        jPanel1.add(btnAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 250, 80));

        btnPay.setBackground(new java.awt.Color(241, 247, 247));
        btnPay.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 153, 0));
        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/pay.png"))); // NOI18N
        btnPay.setText("  Payment");
        btnPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 250, 80));

        btnRep.setBackground(new java.awt.Color(241, 247, 247));
        btnRep.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnRep.setForeground(new java.awt.Color(0, 0, 102));
        btnRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/rep2.png"))); // NOI18N
        btnRep.setText("Employees Report");
        btnRep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepActionPerformed(evt);
            }
        });
        jPanel1.add(btnRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 250, 80));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employees Total Deduction RP");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 270, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Account");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 190, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Employees Total Allowance RP");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 40));

        lblSlide_Login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlide_Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/payroll2.jpeg"))); // NOI18N
        lblSlide_Login1.setPreferredSize(new java.awt.Dimension(1049, 749));
        jPanel1.add(lblSlide_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 580));

        lblSlide_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlide_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/payroll2.jpeg"))); // NOI18N
        lblSlide_Login.setPreferredSize(new java.awt.Dimension(1049, 749));
        jPanel1.add(lblSlide_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 580));

        lblTime1.setBackground(new java.awt.Color(38, 17, 87));
        lblTime1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblTime1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        int DialogButton = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Warning", JOptionPane.YES_NO_OPTION);

        if(DialogButton == JOptionPane.YES_OPTION){

            Login info = new Login();
            info.setVisible(true);
            this.dispose();

        }else{

        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        // TODO add your handling code here:
        EmpMGT rs = new EmpMGT();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnUpSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpSalActionPerformed
        // TODO add your handling code here:
        UpdateSalaryPage rs = new UpdateSalaryPage();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpSalActionPerformed

    private void btnDedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDedActionPerformed
        // TODO add your handling code here:
        DeductionPage rs = new DeductionPage();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDedActionPerformed

    private void btnAllowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowActionPerformed
        // TODO add your handling code here:
        AllowancePage rs = new AllowancePage();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAllowActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        PaymentPage rs = new PaymentPage();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRepActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        UserAccount rs = new UserAccount();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel F_user;
    public static javax.swing.JLabel F_user3;
    private javax.swing.JButton btnAllow;
    private javax.swing.JButton btnDed;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnRep;
    private javax.swing.JButton btnUpSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSlide_Login;
    private javax.swing.JLabel lblSlide_Login1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    // End of variables declaration//GEN-END:variables
}
