package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class PaymentPage extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    String dd, dd1, dd2;
    String fn, ln, mn, ll, pg, dp, yr, fc;
    String ns, mt, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, t1, t2, t3, t4, rm;
    
    
    int rowCount = -1;
    public PaymentPage() {
        initComponents();
        
          
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
   
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        std_panel = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFirstname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFirstname3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAdd_Student1 = new javax.swing.JButton();
        txtFirstname23 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtFirstname2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFirstname9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFirstname10 = new javax.swing.JTextField();
        txtFirstname16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtFirstname24 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtFirstname5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFirstname11 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtFirstname17 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtFirstname22 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnAdd_Student = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_panel.setBackground(new java.awt.Color(255, 255, 255));
        std_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        std_panel.setMinimumSize(new java.awt.Dimension(932, 611));
        std_panel.setPreferredSize(new java.awt.Dimension(932, 611));
        std_panel.setRequestFocusEnabled(false);
        std_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname.setEnabled(false);
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel6.setText("First name : ");
        std_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 30));

        txtFirstname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname1.setEnabled(false);
        std_panel.add(txtFirstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 250, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel7.setText("Middle name : ");
        std_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 30));

        txtFirstname3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname3.setEnabled(false);
        std_panel.add(txtFirstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, 30));

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setText("Date of Birth : ");
        std_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 30));

        jLabel19.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel19.setText("Surname : ");
        std_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 30));

        btnAdd_Student1.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student1.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/rep.png"))); // NOI18N
        btnAdd_Student1.setText("Generate Slip");
        btnAdd_Student1.setEnabled(false);
        btnAdd_Student1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAdd_Student1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_Student1ActionPerformed(evt);
            }
        });
        std_panel.add(btnAdd_Student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 40));

        txtFirstname23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname23.setEnabled(false);
        std_panel.add(txtFirstname23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, 30));

        jLabel29.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel29.setText("Employee ID : ");
        std_panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));

        txtFirstname2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname2.setEnabled(false);
        txtFirstname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname2ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 250, 30));

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel8.setText("Date Employed : ");
        std_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, 30));

        txtFirstname9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname9.setEnabled(false);
        std_panel.add(txtFirstname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 250, 30));

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel9.setText("Job Title : ");
        std_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 110, 30));

        txtFirstname10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname10.setEnabled(false);
        std_panel.add(txtFirstname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 250, 30));

        txtFirstname16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname16.setEnabled(false);
        std_panel.add(txtFirstname16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 250, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setText("Basic Salary : ");
        std_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 30));

        jLabel25.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel25.setText("Status : ");
        std_panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 110, 30));

        txtFirstname24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname24.setEnabled(false);
        std_panel.add(txtFirstname24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 250, 30));

        jLabel30.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel30.setText("Designation : ");
        std_panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 110, 30));

        txtFirstname5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname5.setEnabled(false);
        txtFirstname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname5ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 250, 30));

        jPanel1.setBackground(new java.awt.Color(250, 249, 249));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/emp3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        std_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 210, 200));

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel12.setText("Department : ");
        std_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 30));

        txtFirstname11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname11.setEnabled(false);
        txtFirstname11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname11ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 250, 30));

        jLabel31.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel31.setText("Basic Salary : ");
        std_panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 100, 30));

        txtFirstname17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname17.setEnabled(false);
        std_panel.add(txtFirstname17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 250, 30));

        jPanel3.add(std_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1100, 470));

        jPanel4.setBackground(new java.awt.Color(245, 245, 246));

        btnUpdate3.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate3.setText("HOME");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 80, 30));

        jLabel34.setBackground(new java.awt.Color(0, 204, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/logo.png"))); // NOI18N
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, 120, 70));

        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Generate Payment Slip");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 30));

        jPanel5.setBackground(new java.awt.Color(245, 245, 246));

        txtFirstname22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Perpetua", 2, 18)); // NOI18N
        jLabel28.setText("Search by ID or Surname : ");

        btnAdd_Student.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd_Student.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/sec.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFirstname22, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd_Student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFirstname22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 460, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtFirstname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname2ActionPerformed

    private void txtFirstname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname5ActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
        MainForm rs = new MainForm();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void txtFirstname11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname11ActionPerformed

    private void btnAdd_Student1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_Student1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd_Student1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd_Student;
    public static javax.swing.JButton btnAdd_Student1;
    public static javax.swing.JButton btnUpdate3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel std_panel;
    public static javax.swing.JTextField txtFirstname;
    public static javax.swing.JTextField txtFirstname1;
    public static javax.swing.JTextField txtFirstname10;
    public static javax.swing.JTextField txtFirstname11;
    public static javax.swing.JTextField txtFirstname16;
    public static javax.swing.JTextField txtFirstname17;
    public static javax.swing.JTextField txtFirstname2;
    public static javax.swing.JTextField txtFirstname22;
    public static javax.swing.JTextField txtFirstname23;
    public static javax.swing.JTextField txtFirstname24;
    public static javax.swing.JTextField txtFirstname3;
    public static javax.swing.JTextField txtFirstname5;
    public static javax.swing.JTextField txtFirstname9;
    // End of variables declaration//GEN-END:variables
}
