package payroll_sys;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class UserAccount extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    String dd, dd1, dd2;
    String fn, ln, mn, ll, pg, dp, yr, fc;
    String ns, mt, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, t1, t2, t3, t4, rm;
    
    
    int rowCount = -1;
    public UserAccount() {
        initComponents();
        
          
        //this.setExtendedState(Frame.MAXIMIZED_BOTH);
        
        //this.setUndecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
   
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        std_panel = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFirstname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFirstname3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFirstname4 = new javax.swing.JTextField();
        txtFirstname12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnAdd_Student1 = new javax.swing.JButton();
        btnAdd_Student2 = new javax.swing.JButton();
        btnAdd_Student3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtFirstname13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate3 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        std_panel.setBackground(new java.awt.Color(255, 255, 255));
        std_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        std_panel.setMinimumSize(new java.awt.Dimension(932, 611));
        std_panel.setPreferredSize(new java.awt.Dimension(932, 611));
        std_panel.setRequestFocusEnabled(false);
        std_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 280, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel6.setText("First name : ");
        std_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 110, 30));

        txtFirstname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        std_panel.add(txtFirstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 290, 30));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel7.setText("Middle name : ");
        std_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 110, 30));

        txtFirstname3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        std_panel.add(txtFirstname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 280, 30));

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setText("Username : ");
        std_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 110, 30));

        txtFirstname4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname4ActionPerformed(evt);
            }
        });
        std_panel.add(txtFirstname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 280, 30));

        txtFirstname12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        std_panel.add(txtFirstname12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 290, 30));

        jLabel20.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel20.setText("Email : ");
        std_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 100, 30));

        btnUpdate1.setBackground(new java.awt.Color(163, 192, 192));
        btnUpdate1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(219, 6, 6));
        btnUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/clr.png"))); // NOI18N
        btnUpdate1.setText("Clear");
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 140, 40));

        jLabel19.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel19.setText("Surname : ");
        std_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SURNAME", "FIRST NAME", "EMAIL", "USERNAME", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(table);

        std_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1060, 250));

        btnAdd_Student1.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student1.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/save.png"))); // NOI18N
        btnAdd_Student1.setText("Add Record");
        btnAdd_Student1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnAdd_Student1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 40));

        btnAdd_Student2.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student2.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student2.setForeground(new java.awt.Color(255, 0, 0));
        btnAdd_Student2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/del.png"))); // NOI18N
        btnAdd_Student2.setText("Delete");
        btnAdd_Student2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        std_panel.add(btnAdd_Student2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 120, 30));

        btnAdd_Student3.setBackground(new java.awt.Color(163, 192, 192));
        btnAdd_Student3.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btnAdd_Student3.setForeground(new java.awt.Color(16, 107, 35));
        btnAdd_Student3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/upd.png"))); // NOI18N
        btnAdd_Student3.setText("Update");
        btnAdd_Student3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAdd_Student3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_Student3ActionPerformed(evt);
            }
        });
        std_panel.add(btnAdd_Student3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 130, 30));

        jLabel10.setFont(new java.awt.Font("MS Gothic", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 0));
        jLabel10.setText("Create new user account here");
        std_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 310, 30));

        txtFirstname13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        std_panel.add(txtFirstname13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 290, 30));

        jLabel21.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel21.setText("Password : ");
        std_panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 100, 30));

        jPanel3.add(std_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1100, 600));

        jPanel4.setBackground(new java.awt.Color(245, 245, 246));

        btnUpdate3.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate3.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate3.setText("HOME");
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 80, 30));

        jLabel34.setBackground(new java.awt.Color(0, 204, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll_sys/logo.png"))); // NOI18N
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 0, 120, 70));

        jLabel17.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("User Account");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname4ActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
        // TODO add your handling code here:
        MainForm rs = new MainForm();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void btnAdd_Student3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_Student3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd_Student3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdd_Student1;
    public static javax.swing.JButton btnAdd_Student2;
    public static javax.swing.JButton btnAdd_Student3;
    public static javax.swing.JButton btnUpdate1;
    public static javax.swing.JButton btnUpdate3;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JPanel std_panel;
    private javax.swing.JTable table;
    public static javax.swing.JTextField txtFirstname;
    public static javax.swing.JTextField txtFirstname1;
    public static javax.swing.JTextField txtFirstname12;
    public static javax.swing.JTextField txtFirstname13;
    public static javax.swing.JTextField txtFirstname3;
    public static javax.swing.JTextField txtFirstname4;
    // End of variables declaration//GEN-END:variables
}
